"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('$HOME/.vim/dein')
  call dein#begin('$HOME/.vim/dein')

  " Let dein manage dein
  " Required:
  call dein#add('$HOME/.vim/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('morhetz/gruvbox')
  call dein#add('ctrlpvim/ctrlp.vim')
  call dein#add('ntpeters/vim-better-whitespace')
  call dein#add('nvie/vim-flake8')
  call dein#add('airblade/vim-gitgutter')
  call dein#add('tpope/vim-unimpaired')
  call dein#add('scrooloose/nerdtree')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable
"End dein Scripts-------------------------

let g:airline_powerline_fonts = 1
let g:airline_theme='bubblegum'
let g:airline#extensions#tabline#enabled = 1

colorscheme gruvbox
set background=dark

set cursorline
set number
set colorcolumn=80
set showcmd " Show active command (like pressed leader)
let mapleader=" "
set hidden " hide buffers which allows opening/changing buffers without writing first
set hlsearch
set incsearch

nmap <silent> <Leader>/ :nohlsearch<CR>
nmap <Leader>n :NERDTreeToggle<CR>
nmap <Leader>t :TlistToggle<CR>
